try{
    criticalCode();
}
catch(ex){
    console.log("Got an error!!!!!!!!!!!!!!");
    logError(ex);
}